// Code generated by protoc-gen-go. DO NOT EDIT.
// source: msg_notification.proto

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/mwitkow/go-proto-validators"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type MsgNotificationRequest struct {
	Content              string   `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	Type                 int32    `protobuf:"varint,2,opt,name=type,proto3" json:"type,omitempty"`
	Group                uint64   `protobuf:"varint,3,opt,name=group,proto3" json:"group,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgNotificationRequest) Reset()         { *m = MsgNotificationRequest{} }
func (m *MsgNotificationRequest) String() string { return proto.CompactTextString(m) }
func (*MsgNotificationRequest) ProtoMessage()    {}
func (*MsgNotificationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_msg_notification_49477be40ff6cd00, []int{0}
}
func (m *MsgNotificationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgNotificationRequest.Unmarshal(m, b)
}
func (m *MsgNotificationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgNotificationRequest.Marshal(b, m, deterministic)
}
func (dst *MsgNotificationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgNotificationRequest.Merge(dst, src)
}
func (m *MsgNotificationRequest) XXX_Size() int {
	return xxx_messageInfo_MsgNotificationRequest.Size(m)
}
func (m *MsgNotificationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgNotificationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MsgNotificationRequest proto.InternalMessageInfo

func (m *MsgNotificationRequest) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *MsgNotificationRequest) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *MsgNotificationRequest) GetGroup() uint64 {
	if m != nil {
		return m.Group
	}
	return 0
}

type MsgNotificationResponse struct {
	Status               string   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Code                 int32    `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgNotificationResponse) Reset()         { *m = MsgNotificationResponse{} }
func (m *MsgNotificationResponse) String() string { return proto.CompactTextString(m) }
func (*MsgNotificationResponse) ProtoMessage()    {}
func (*MsgNotificationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_msg_notification_49477be40ff6cd00, []int{1}
}
func (m *MsgNotificationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgNotificationResponse.Unmarshal(m, b)
}
func (m *MsgNotificationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgNotificationResponse.Marshal(b, m, deterministic)
}
func (dst *MsgNotificationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgNotificationResponse.Merge(dst, src)
}
func (m *MsgNotificationResponse) XXX_Size() int {
	return xxx_messageInfo_MsgNotificationResponse.Size(m)
}
func (m *MsgNotificationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgNotificationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgNotificationResponse proto.InternalMessageInfo

func (m *MsgNotificationResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *MsgNotificationResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func init() {
	proto.RegisterType((*MsgNotificationRequest)(nil), "msg.notification.MsgNotificationRequest")
	proto.RegisterType((*MsgNotificationResponse)(nil), "msg.notification.MsgNotificationResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgNotificationClient is the client API for MsgNotification service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgNotificationClient interface {
	CheckIn(ctx context.Context, in *MsgNotificationRequest, opts ...grpc.CallOption) (*MsgNotificationResponse, error)
}

type msgNotificationClient struct {
	cc *grpc.ClientConn
}

func NewMsgNotificationClient(cc *grpc.ClientConn) MsgNotificationClient {
	return &msgNotificationClient{cc}
}

func (c *msgNotificationClient) CheckIn(ctx context.Context, in *MsgNotificationRequest, opts ...grpc.CallOption) (*MsgNotificationResponse, error) {
	out := new(MsgNotificationResponse)
	err := c.cc.Invoke(ctx, "/msg.notification.MsgNotification/CheckIn", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgNotificationServer is the server API for MsgNotification service.
type MsgNotificationServer interface {
	CheckIn(context.Context, *MsgNotificationRequest) (*MsgNotificationResponse, error)
}

func RegisterMsgNotificationServer(s *grpc.Server, srv MsgNotificationServer) {
	s.RegisterService(&_MsgNotification_serviceDesc, srv)
}

func _MsgNotification_CheckIn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgNotificationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgNotificationServer).CheckIn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/msg.notification.MsgNotification/CheckIn",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgNotificationServer).CheckIn(ctx, req.(*MsgNotificationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _MsgNotification_serviceDesc = grpc.ServiceDesc{
	ServiceName: "msg.notification.MsgNotification",
	HandlerType: (*MsgNotificationServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CheckIn",
			Handler:    _MsgNotification_CheckIn_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "msg_notification.proto",
}

func init() {
	proto.RegisterFile("msg_notification.proto", fileDescriptor_msg_notification_49477be40ff6cd00)
}

var fileDescriptor_msg_notification_49477be40ff6cd00 = []byte{
	// 262 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x90, 0x31, 0x4f, 0xc3, 0x30,
	0x10, 0x85, 0x95, 0x92, 0xb6, 0xc2, 0x0b, 0xc8, 0x42, 0x21, 0x8a, 0x18, 0xa2, 0x4e, 0x61, 0xa8,
	0x2d, 0x81, 0xc4, 0x0f, 0x00, 0x31, 0x30, 0xc0, 0x90, 0x11, 0x21, 0x90, 0xe3, 0x1a, 0xd7, 0x6a,
	0xe3, 0x73, 0x73, 0x17, 0x2a, 0xfe, 0x3d, 0x6a, 0x52, 0xaa, 0xaa, 0x30, 0x74, 0x7b, 0xcf, 0x7e,
	0xfa, 0xee, 0xee, 0xb1, 0xa4, 0x46, 0xfb, 0xe1, 0x81, 0xdc, 0xa7, 0xd3, 0x8a, 0x1c, 0x78, 0x11,
	0x1a, 0x20, 0xe0, 0xe7, 0x35, 0x5a, 0xb1, 0xff, 0x9e, 0xdd, 0x59, 0x47, 0xf3, 0xb6, 0x12, 0x1a,
	0x6a, 0x59, 0xaf, 0x1d, 0x2d, 0x60, 0x2d, 0x2d, 0x4c, 0xbb, 0xf8, 0xf4, 0x4b, 0x2d, 0xdd, 0x4c,
	0x11, 0x34, 0x28, 0x77, 0xb2, 0x27, 0x65, 0x57, 0x16, 0xc0, 0x2e, 0x8d, 0x54, 0xc1, 0x49, 0xe5,
	0x3d, 0x50, 0x87, 0xc3, 0xfe, 0x77, 0xf2, 0xc6, 0x92, 0x67, 0xb4, 0x2f, 0x7b, 0x83, 0x4a, 0xb3,
	0x6a, 0x0d, 0x12, 0x4f, 0xd9, 0x58, 0x83, 0x27, 0xe3, 0x29, 0x8d, 0xf2, 0xa8, 0x38, 0x2d, 0x7f,
	0x2d, 0xe7, 0x2c, 0xa6, 0xef, 0x60, 0xd2, 0x41, 0x1e, 0x15, 0xc3, 0xb2, 0xd3, 0xfc, 0x82, 0x0d,
	0x6d, 0x03, 0x6d, 0x48, 0x4f, 0xf2, 0xa8, 0x88, 0xcb, 0xde, 0x4c, 0x1e, 0xd9, 0xe5, 0x1f, 0x3a,
	0x06, 0xf0, 0x68, 0x78, 0xc2, 0x46, 0x48, 0x8a, 0x5a, 0xdc, 0xd2, 0xb7, 0x6e, 0x03, 0xd7, 0x30,
	0xdb, 0xc1, 0x37, 0xfa, 0x66, 0xc5, 0xce, 0x0e, 0x30, 0xfc, 0x9d, 0x8d, 0x1f, 0xe6, 0x46, 0x2f,
	0x9e, 0x3c, 0x2f, 0xc4, 0x61, 0x57, 0xe2, 0xff, 0x93, 0xb2, 0xeb, 0x23, 0x92, 0xfd, 0x7a, 0xf7,
	0xf1, 0xeb, 0x20, 0x54, 0xd5, 0xa8, 0x2b, 0xe9, 0xf6, 0x27, 0x00, 0x00, 0xff, 0xff, 0xfb, 0xf8,
	0x25, 0x99, 0xa6, 0x01, 0x00, 0x00,
}
