// Code generated by protoc-gen-go. DO NOT EDIT.
// source: msg_notification.proto

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/mwitkow/go-proto-validators"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type NoticeType int32

const (
	NoticeType_mail   NoticeType = 0
	NoticeType_phone  NoticeType = 1
	NoticeType_wechat NoticeType = 2
)

var NoticeType_name = map[int32]string{
	0: "mail",
	1: "phone",
	2: "wechat",
}
var NoticeType_value = map[string]int32{
	"mail":   0,
	"phone":  1,
	"wechat": 2,
}

func (x NoticeType) String() string {
	return proto.EnumName(NoticeType_name, int32(x))
}
func (NoticeType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_msg_notification_e60cd768f39ff40d, []int{0}
}

type MsgNotificationRequest struct {
	Content              string       `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	NoticeType           []NoticeType `protobuf:"varint,2,rep,packed,name=notice_type,json=noticeType,proto3,enum=msg.notification.NoticeType" json:"notice_type,omitempty"`
	Group                uint64       `protobuf:"varint,3,opt,name=group,proto3" json:"group,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *MsgNotificationRequest) Reset()         { *m = MsgNotificationRequest{} }
func (m *MsgNotificationRequest) String() string { return proto.CompactTextString(m) }
func (*MsgNotificationRequest) ProtoMessage()    {}
func (*MsgNotificationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_msg_notification_e60cd768f39ff40d, []int{0}
}
func (m *MsgNotificationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgNotificationRequest.Unmarshal(m, b)
}
func (m *MsgNotificationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgNotificationRequest.Marshal(b, m, deterministic)
}
func (dst *MsgNotificationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgNotificationRequest.Merge(dst, src)
}
func (m *MsgNotificationRequest) XXX_Size() int {
	return xxx_messageInfo_MsgNotificationRequest.Size(m)
}
func (m *MsgNotificationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgNotificationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MsgNotificationRequest proto.InternalMessageInfo

func (m *MsgNotificationRequest) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *MsgNotificationRequest) GetNoticeType() []NoticeType {
	if m != nil {
		return m.NoticeType
	}
	return nil
}

func (m *MsgNotificationRequest) GetGroup() uint64 {
	if m != nil {
		return m.Group
	}
	return 0
}

type MsgNotificationResponse struct {
	Status               string   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Code                 int32    `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgNotificationResponse) Reset()         { *m = MsgNotificationResponse{} }
func (m *MsgNotificationResponse) String() string { return proto.CompactTextString(m) }
func (*MsgNotificationResponse) ProtoMessage()    {}
func (*MsgNotificationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_msg_notification_e60cd768f39ff40d, []int{1}
}
func (m *MsgNotificationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgNotificationResponse.Unmarshal(m, b)
}
func (m *MsgNotificationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgNotificationResponse.Marshal(b, m, deterministic)
}
func (dst *MsgNotificationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgNotificationResponse.Merge(dst, src)
}
func (m *MsgNotificationResponse) XXX_Size() int {
	return xxx_messageInfo_MsgNotificationResponse.Size(m)
}
func (m *MsgNotificationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgNotificationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgNotificationResponse proto.InternalMessageInfo

func (m *MsgNotificationResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *MsgNotificationResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func init() {
	proto.RegisterType((*MsgNotificationRequest)(nil), "msg.notification.MsgNotificationRequest")
	proto.RegisterType((*MsgNotificationResponse)(nil), "msg.notification.MsgNotificationResponse")
	proto.RegisterEnum("msg.notification.NoticeType", NoticeType_name, NoticeType_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgNotificationClient is the client API for MsgNotification service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgNotificationClient interface {
	CheckIn(ctx context.Context, in *MsgNotificationRequest, opts ...grpc.CallOption) (*MsgNotificationResponse, error)
}

type msgNotificationClient struct {
	cc *grpc.ClientConn
}

func NewMsgNotificationClient(cc *grpc.ClientConn) MsgNotificationClient {
	return &msgNotificationClient{cc}
}

func (c *msgNotificationClient) CheckIn(ctx context.Context, in *MsgNotificationRequest, opts ...grpc.CallOption) (*MsgNotificationResponse, error) {
	out := new(MsgNotificationResponse)
	err := c.cc.Invoke(ctx, "/msg.notification.MsgNotification/CheckIn", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgNotificationServer is the server API for MsgNotification service.
type MsgNotificationServer interface {
	CheckIn(context.Context, *MsgNotificationRequest) (*MsgNotificationResponse, error)
}

func RegisterMsgNotificationServer(s *grpc.Server, srv MsgNotificationServer) {
	s.RegisterService(&_MsgNotification_serviceDesc, srv)
}

func _MsgNotification_CheckIn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgNotificationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgNotificationServer).CheckIn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/msg.notification.MsgNotification/CheckIn",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgNotificationServer).CheckIn(ctx, req.(*MsgNotificationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _MsgNotification_serviceDesc = grpc.ServiceDesc{
	ServiceName: "msg.notification.MsgNotification",
	HandlerType: (*MsgNotificationServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CheckIn",
			Handler:    _MsgNotification_CheckIn_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "msg_notification.proto",
}

func init() {
	proto.RegisterFile("msg_notification.proto", fileDescriptor_msg_notification_e60cd768f39ff40d)
}

var fileDescriptor_msg_notification_e60cd768f39ff40d = []byte{
	// 319 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x90, 0x41, 0x4f, 0xea, 0x40,
	0x14, 0x85, 0x5f, 0xa1, 0xc0, 0xe3, 0xbe, 0xe4, 0xd9, 0x4c, 0x0c, 0x36, 0x84, 0x05, 0x61, 0x55,
	0x4d, 0x68, 0x13, 0x4c, 0xdc, 0xb9, 0xd1, 0xb8, 0x70, 0x21, 0x8b, 0xc6, 0x95, 0x0b, 0xc9, 0x30,
	0x8c, 0xd3, 0x09, 0x74, 0xee, 0xc0, 0xdc, 0x4a, 0xf8, 0x05, 0xfe, 0x6d, 0x43, 0x8b, 0x48, 0xc0,
	0x85, 0xbb, 0x73, 0x66, 0x4e, 0xee, 0xf9, 0xee, 0x85, 0x4e, 0xee, 0xd4, 0xc4, 0x20, 0xe9, 0x37,
	0x2d, 0x38, 0x69, 0x34, 0xb1, 0x5d, 0x21, 0x21, 0x0b, 0x72, 0xa7, 0xe2, 0xc3, 0xf7, 0xee, 0x8d,
	0xd2, 0x94, 0x15, 0xd3, 0x58, 0x60, 0x9e, 0xe4, 0x6b, 0x4d, 0x73, 0x5c, 0x27, 0x0a, 0x87, 0x65,
	0x7c, 0xf8, 0xce, 0x17, 0x7a, 0xc6, 0x09, 0x57, 0x2e, 0xd9, 0xcb, 0x6a, 0x52, 0xb7, 0xa7, 0x10,
	0xd5, 0x42, 0x26, 0xdc, 0xea, 0x84, 0x1b, 0x83, 0x54, 0x8e, 0x73, 0xd5, 0xef, 0xe0, 0xc3, 0x83,
	0xce, 0x93, 0x53, 0xe3, 0x83, 0xa6, 0x54, 0x2e, 0x0b, 0xe9, 0x88, 0x85, 0xd0, 0x12, 0x68, 0x48,
	0x1a, 0x0a, 0xbd, 0xbe, 0x17, 0xb5, 0xd3, 0x2f, 0xcb, 0x6e, 0xe1, 0xdf, 0x16, 0x4d, 0xc8, 0x09,
	0x6d, 0xac, 0x0c, 0x6b, 0xfd, 0x7a, 0xf4, 0x7f, 0xd4, 0x8b, 0x8f, 0x91, 0xe3, 0x71, 0x19, 0x7a,
	0xde, 0x58, 0x99, 0x82, 0xd9, 0x6b, 0x76, 0x0e, 0x0d, 0xb5, 0xc2, 0xc2, 0x86, 0xf5, 0xbe, 0x17,
	0xf9, 0x69, 0x65, 0x06, 0x0f, 0x70, 0x71, 0x02, 0xe2, 0x2c, 0x1a, 0x27, 0x59, 0x07, 0x9a, 0x8e,
	0x38, 0x15, 0x6e, 0x07, 0xb2, 0x73, 0x8c, 0x81, 0x2f, 0x70, 0xb6, 0x05, 0xf0, 0xa2, 0x46, 0x5a,
	0xea, 0xab, 0x21, 0xc0, 0x77, 0x2d, 0xfb, 0x0b, 0x7e, 0xce, 0xf5, 0x22, 0xf8, 0xc3, 0xda, 0xd0,
	0xb0, 0x19, 0x1a, 0x19, 0x78, 0x0c, 0xa0, 0xb9, 0x96, 0x22, 0xe3, 0x14, 0xd4, 0x46, 0x4b, 0x38,
	0x3b, 0x6a, 0x65, 0xaf, 0xd0, 0xba, 0xcf, 0xa4, 0x98, 0x3f, 0x1a, 0x16, 0x9d, 0xee, 0xf4, 0xf3,
	0xb1, 0xba, 0x97, 0xbf, 0x48, 0x56, 0xdb, 0xdc, 0xf9, 0x2f, 0x35, 0x3b, 0x9d, 0x36, 0xcb, 0xfb,
	0x5f, 0x7f, 0x06, 0x00, 0x00, 0xff, 0xff, 0x7d, 0xa0, 0x5e, 0x20, 0x01, 0x02, 0x00, 0x00,
}
